name: build

on: [push, pull_request]

jobs:
  list-examples:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        # Use ls and jq to populate a JSON array of tested files 
        run: >
          echo "::set-output name=matrix::$(find json-esimerkit -type f -name "SpatialPlan-*.json" | sed 's|\.json||' | jq -R -s -c 'split("\n")[:-1]')"
  
  ryhti-validate:
    needs: list-examples
    runs-on: ubuntu-latest
    strategy:
        matrix:
            file: ${{ fromJson(needs.list-examples.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - id: pick-plan-type
        run: echo "pt=$(jq -r '.planType' ${{ matrix.file }}.meta)" >> "$GITHUB_OUTPUT"
      - id: pick-admin-area-ids
        run: echo "aai=$(jq -r '.administrativeAreaIdentifiers' ${{ matrix.file }}.meta)" >> "$GITHUB_OUTPUT"
      - id: validation
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api-test.ymparisto.fi/ryhti/plan-public/api/Plan/Validate?planType=${{ steps.pick-plan-type.outputs.pt }}&administrativeAreaIdentifiers=${{ steps.pick-admin-area-ids.outputs.aai }}'
          method: 'POST'
          customHeaders: '{"acccept":"*/*","Content-Type": "application/json","Ocp-Apim-Subscription-Key":"${{ secrets.API_KEY }}"}'
          file: ${{ matrix.file }}.json
          preventFailureOnNoResponse: true
    