name: onPush

on: [push]

jobs:
  list-examples:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matr }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        # Use find and jq to populate a JSON array of example files 
        run: >
          echo "matr=$(find json-esimerkit -type f -name "SpatialPlan-*.yml" | sed 's|\.yml||' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
  ryhti-validate:
    needs: list-examples
    runs-on: ubuntu-latest
    strategy:
        matrix:
            file: ${{ fromJson(needs.list-examples.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - id: pick-plan-type
        run: echo "pt=$(jq -r '.planType' ${{ matrix.file }}.meta)" >> "$GITHUB_OUTPUT"
      - id: pick-admin-area-ids
        run: echo "aai=$(jq -r '.administrativeAreaIdentifiers' ${{ matrix.file }}.meta)" >> "$GITHUB_OUTPUT"
      - id: json-from-yaml
        run: echo "result=$(yq -o=json -I0 eval ${{ matrix.file }}.yml)" >> "$GITHUB_OUTPUT"
      - id: validation
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api-test.ymparisto.fi/ryhti/plan-public/api/Plan/Validate?planType=${{ steps.pick-plan-type.outputs.pt }}&administrativeAreaIdentifiers=${{ steps.pick-admin-area-ids.outputs.aai }}'
          method: 'POST'
          customHeaders: '{"acccept":"*/*","Content-Type": "application/json","Ocp-Apim-Subscription-Key":"${{ secrets.API_KEY }}"}'
          #file: ${{ matrix.file }}.json
          data: '${{ steps.json-from-yaml.outputs.result }}'
          preventFailureOnNoResponse: true
      - id: md-gen
        run: |
          echo "# ${{ matrix.file }} " > ${{ matrix.file }}.md
          echo "Automaattisesti generoitu YAML-tiedostosta ${{ matrix.file }}.yml" >> ${{ matrix.file }}.md. Älä muokkaa suoraan.
          echo "" >> ${{ matrix.file }}.md
          echo "Generointiaika: $(date)" >> ${{ matrix.file }}.md
          echo '```json' >> ${{ matrix.file }}.md
          echo "$(yq -o=json eval ${{ matrix.file }}.yml)" >> ${{ matrix.file }}.md
          echo '```' >> ${{ matrix.file }}.md
      - id: commit_files
        name: Commit files
        run: |
          git config --local user.name "actions-user[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git diff --exit-code
          if [ $? -eq 0 ]; then
            git add ${{ matrix.file }}.md
            git commit -am "Generated MD file ${{ matrix.file }}.md"
            git push
          fi