name: onPush

on: [push]

jobs:
  list-examples:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matr }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        # Use find and jq to populate a JSON array of example files for the matrix
        run: >
          echo "matr=$(find json-esimerkit -type f -name "SpatialPlan-*.yml" | sed 's|\.yml||' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
  ryhti-validate:
    needs: list-examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.list-examples.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - id: md-gen
        run: |
          echo "existedBefore=$(test -f ${{ matrix.file }}.md && echo 1)" >> "$GITHUB_OUTPUT"
          echo "# ${{ matrix.file }} " > ${{ matrix.file }}.md
          echo "Automaattisesti generoitu YAML-tiedostosta ${{ matrix.file }}.yml. Älä muokkaa tätä tiedostoa käsin." >> ${{ matrix.file }}.md
          echo '```json' >> ${{ matrix.file }}.md
          echo "$(yq -o=json eval ${{ matrix.file }}.yml)" >> ${{ matrix.file }}.md
          echo '```' >> ${{ matrix.file }}.md
      - id: commit-update
        if: ${{ steps.md-gen.outputs.existedBefore }}
        run: |
          git config --local user.name "actions-user[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git pull --ff-only
          git diff --quiet || (git add -f ${{ matrix.file }}.md && git commit -m "Updated MD file ${{ matrix.file }}.md")
          git push
      - id: commit-new
        if: ${{ ! steps.md-gen.outputs.existedBefore }}
        run: |
          git config --local user.name "actions-user[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git pull --ff-only
          git add -f ${{ matrix.file }}.md
          git commit -m "Created MD file ${{ matrix.file }}.md"
          git push
      - id: pick-plan-type
        run: echo "pt=$(yq -r '.planType' ${{ matrix.file }}.meta)" >> "$GITHUB_OUTPUT"
      - id: pick-admin-area-ids
        run: echo "aai=$(yq -r '.administrativeAreaIdentifiers' ${{ matrix.file }}.meta)" >> "$GITHUB_OUTPUT"
      - id: json-from-yaml
        run: echo "result=$(yq -o=json -I0 eval ${{ matrix.file }}.yml)" >> "$GITHUB_OUTPUT"
      - id: validation
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.ymparisto.fi/ryhti/plan-public/api/Plan/Validate?planType=${{ steps.pick-plan-type.outputs.pt }}&administrativeAreaIdentifiers=${{ steps.pick-admin-area-ids.outputs.aai }}'
          method: 'POST'
          customHeaders: '{"acccept":"*/*","Content-Type": "application/json","Ocp-Apim-Subscription-Key":"${{ secrets.API_KEY_PROD }}"}'
          data: '${{ steps.json-from-yaml.outputs.result }}'
          preventFailureOnNoResponse: true
      